import { BaseEntity } from "../base-entity";

export class LBSACPVendor extends BaseEntity{
    CompanyID:any;
    VendorCode  :any;
    VendorAccountName  :any;
    TaxIdentificationNumber :any;
    TradingName :any;
    CompanyName :any;
    ProprietorName :any;
    Laddr1 :any;
    Laddr2;any;
    Laddr3:any;
    Paddr1 :any;
    Paddr2:any;
    Paddr3:any;
    ZipCode :any;
    Phone :any;
    Fax :any;
    EmailAddress :any;
    TradingStatus :any;
    BankAccountName :any;
    BankName :any;
    BankAccountNumber :any;
    BSB :any;
    BankSwiftCode :any;
    DefaultPaymentType :any;
    CreditLimit :any;
    LastPurchaseDate :any;
    LastPaymentDate :any;
    TermsDays :any;
    PurchaseOrderValidityDays :any;
    CurrentBalance :any;
    Period1 :any;
    Period2:any;
    Period3:any;
    Period4 :any;
    UseForeignCurrency :any;
    CurrencyID :any;
    FXCurrentBalance :any;
    FXPeriod1 :any;
    FXPeriod2 :any;
    FXPeriod3 :any;
    FXPeriod4:any;
    DefaultPurchaseOrderWorkflow  :any;
    Country :any;
    State :any;
    City :any;
    WorkflowCode:any;
    WorkFlowName:any;
    CurrencyCode:any;
    CurrecnyName:any;
    CountryCode:any;
    CountryName:any;
    StateCode:any;
    StateName:any;
    CityCode:any;
    CityName:any;
}
